title:
  en: Yvonne Ru
  zh: 茹意
subtitle:
  en: "Hello, I'm Yvonne Ru, PhD Candidate and Researcher at University of Toronto."
  zh: "你好，我是茹意，目前在多伦多大学读博。"
introduction:
  en: >
    <h1>Hello, I'm <a href="/about/">Yvonne Ru</a>, PhD Candidate and Researcher at University of Toronto.</h1>
    <h2>Also an entrepreneur, an avid swimmer, and a world traveler. I always try my very best.</h2>
  zh: >
    <h1>你好，我是<a href="/关于/">茹意</a>，目前在多伦多大学读博，从事人工智能方面研究工作。</h1>
    <h2>独行的静心驻足和思考，相聚的感动笑谈与成长，滴滴在心。加油，把自己能做的一切做到最好。</h2>
keywords: "Yvonne Ru,Yi Ru,Ru Yi,茹意"
author:
  name: Yvonne Ru
  email: hello@yvonneru.com
timezone: UTC
encoding: utf-8

url: http://www.yvonneru.com
repository: https://github.com/ruyiblog/ruyiblog.github.io
feed:
  en: /feed.xml
  zh: /订阅.xml
static_url: /static

debug: false
analytics: UA-34085887-4

lsi: false
safe: true
highlighter: rouge
permalink: /:year/:month/:title/
relative_permalinks: false
markdown: kramdown

exclude:
- Gemfile
- Gemfile.lock
- Makefile
- Rakefile
- README.md
- LICENSE

defaults:
- scope:
    path: ""
    type: posts
  values:
    is_post: true

primary_color: "#fe9a3d"

